### ISSUE TITLE
Stale src files aren't recompiled

### ISSUE THREAD

**Issue by refractalize** [dsc/connect-compiler#5]
Latest version of express, latest version of connect-compiler, and this code:

```
var express = require('express');
var compiler = require('connect-compiler');

var app = express.createServer();
pub = __dirname + '/public';
app.use (express.static (pub));
app.use (compiler ({src: pub, enabled: ['less']}));

app.listen(4100);
```

Write something in public/style.less, GET it, and then change it a few times: it doesn't update.

Any ideas?

**Comment by dsc** [comment]
Hm. I will look into it.

**Comment by evdb** [comment]
You need to put the express.static middleware after the compiler - otherwise it serves the file and ends the request before the compiler has a chance to run.

**Comment by refractalize** [comment]
That makes total sense - cheers

**Comment by dsc** [comment]
refractalize is totally right. I didn't read carefully :)
